# Generated by Django 5.1.1 on 2025-02-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cart_size_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='app.size'),
            preserve_default=False,
        ),
    ]
