# Generated by Django 4.2.16 on 2025-02-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
