# Generated by Django 4.2.16 on 2024-12-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_city_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dis',
            field=models.TextField(default='dis'),
            preserve_default=False,
        ),
    ]
