# Generated by Django 4.2.16 on 2024-12-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='size',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='app.size'),
        ),
    ]
