# Generated by Django 4.2.16 on 2024-12-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_size_prod_remove_size_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='size',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='app.size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app.size'),
            preserve_default=False,
        ),
    ]
