# Generated by Django 5.1.5 on 2025-01-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_user_alter_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
